# Generated by Django 4.0.3 on 2022-03-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('icompany_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('scompany_name', models.CharField(max_length=500)),
                ('dcreated_date', models.DateField()),
                ('dupdated_date', models.DateField()),
                ('screated_by', models.CharField(max_length=500)),
                ('supdated_by', models.CharField(max_length=500)),
                ('cstatus', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EngineerAction',
            fields=[
                ('iengineer_action_id', models.AutoField(primary_key=True, serialize=False)),
                ('iuser_request_id', models.IntegerField()),
                ('irequest_type_id', models.IntegerField()),
                ('stask_name', models.CharField(max_length=500)),
                ('stask_description', models.CharField(max_length=500)),
                ('scode_files_altered', models.CharField(max_length=500)),
                ('dtask_date', models.DateField()),
                ('dcreated_date', models.DateField()),
                ('dupdated_date', models.DateField()),
                ('screated_by', models.CharField(max_length=500)),
                ('supdated_by', models.CharField(max_length=500)),
                ('cstatus', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('irequest_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('srequest_type_name', models.CharField(max_length=500)),
                ('srequest_type_description', models.CharField(max_length=500)),
                ('dcreated_date', models.DateField()),
                ('dupdated_date', models.DateField()),
                ('screated_by', models.CharField(max_length=500)),
                ('supdated_by', models.CharField(max_length=500)),
                ('cstatus', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('iuser_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('sproblem_name', models.CharField(max_length=500)),
                ('sproblem_description', models.CharField(max_length=500)),
                ('icompany_id', models.IntegerField()),
                ('cresolution_status', models.CharField(max_length=1)),
                ('ddate_raised', models.DateField()),
                ('dcreated_date', models.DateField()),
                ('dupdated_date', models.DateField()),
                ('screated_by', models.CharField(max_length=500)),
                ('supdated_by', models.CharField(max_length=500)),
                ('cstatus', models.CharField(max_length=1)),
            ],
        ),
    ]
